version: "3.0"
services:
  mobilitydb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data_db:/var/lib/postgresql/data
    ports:
      - 45432:5432
    env_file:
      - .env
    restart: on-failure
  grafana:
    image: grafana/grafana-enterprise
    # image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=foursquare-studio-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_SERVER_DOMAIN=ubica.app
      - GF_SERVER_ROOT_URL=https://ubica.app/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_PROXY_WHITELIST=
      - GF_PANELS_ENABLE_ALPHA=true
    volumes:
      - ./grafana-data:/var/lib/grafana
  dagster:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    ports:
      - 4000:3000
    volumes:
      - ./data:/opt/dagster/app/data
      - .:/opt/dagster/app
    env_file:
      - .env

    # environment:
    #   DAGSTER_HOME: "/opt/dagster/app"
    #   POSTGRES_DB=: "lactalab"
    #   POSTGRES_USER: "llactalab"
    #   POSTGRES_PASSWORD: "movilidad.llactalabs"
    #   POSTGRES_PORT: 5432
    #   POSTGRES_HOST: "mobilitydb"
    #   LANG: "es_ES.utf8"
