rumbos-pgs:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: llactalab
      password: movilidad.llactalabs
      port: 45432
      dbname: llactalab-piloto3
      schema: public
      # user: "{{ env_var('DBT_USER') }}"
      # password: "{{ env_var('DBT_PASSWORD') }}"

